[package]
name = "yassg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["derive"] }
html-escape = "0.2.13"
crossterm = "0.27.0"
pulldown-cmark = "0.10.0"
mlua = { version = "0.9.5", features = ["lua54"] }
notify-debouncer-mini = "0.4.1"
rsass = "0.28.8"
toml = "0.8.10"
serde = { version = "1.0.197", features = ["derive"] }
