[rust]
extentions = ["rs"]
keywords = "[pub|crate|fn|struct|impl|use|trait|enum]"
symbols = "[{|}]"
fun = "fn"

[haskell]
extentions = ["hs", "lhs"]
keywords = "import"

[javascript]
extentions = ["js", "mjs", "jsx"]
keywords = "function|class|import"
