[rust]
extentions = ["rs"]
comment = '\/\/.*|\/\*(.|\n)*\*\/'
keyword = 'abstract|alignof|as|become|box|break|const|continue|crate|do|else|enum|extern|false|final|fn|for|if|impl|in|let|loop|macro|match|mod|move|mut|offsetof|override|priv|pub|pure|ref|return|sizeof|static|self|struct|super|true|trait|type|typeof|unsafe|unsized|use|virtual|where|while|yield'
macro = '(\w|_)(\w|\d|_)*!'
constant = '[A-Z][A-Z_]*'
type = '[A-Z]\w*'
string = '"(.|\n)*"'

[haskell]
extentions = ["hs", "lhs"]
keywords = "import"

[javascript]
extentions = ["js", "mjs", "jsx"]
keywords = "function|class|import"
